# .github/workflows/main.yml

name: Run HR Vision Agent

on:
  schedule:
    # 👇👇👇 ИЗМЕНЕНИЕ ЗДЕСЬ 👇👇👇
    # Запуск каждые 15 минут, с 9:00 до 16:00 по МСК (что равно 6:00-13:00 UTC)
    - cron: '*/15 6-13 * * *'
  
  # Позволяет запускать этот воркфлоу вручную со страницы Actions
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 4. Run Python script
      run: python main.py
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SESSION_NAME: ${{ secrets.SESSION_NAME }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}