name: Run HR Vision Agent

on:
  # Позволяет запускать этот воркфлоу вручную и через внешние сервисы (API)
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Cache installed Python packages
      id: pip-cache
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: ${{ runner.os }}-python-3.10-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-3.10-

    - name: 4. Install dependencies if cache not found
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt --user

    - name: 5. Add user bin to PATH and run script
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        python -u main.py
      env:
        # 👇 ИЗМЕНЕНИЯ ЗДЕСЬ
        NEON_DB_CONNECTION_STRING: ${{ secrets.NEON_DB_CONNECTION_STRING }}
        # 👆 SUPABASE_URL и SUPABASE_KEY УДАЛЕНЫ
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SESSION_NAME: ${{ secrets.SESSION_NAME }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}