name: Run HR Vision Agent

on:
  schedule:
    # Запуск каждые 5 минут, с 8:00 до 17:00 по МСК (что равно 5:00-14:00 UTC)
    - cron: '*/5 5-14 * * *'
  
  # Позволяет запускать этот воркфлоу вручную со страницы Actions
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Cache installed Python packages
      id: pip-cache
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python-version }}-

    - name: 4. Install dependencies if cache not found
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt --user

    - name: 5. Add user bin to PATH and run script
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        # ИЗМЕНЕНИЕ ЗДЕСЬ: добавлен флаг -u
        python -u main.py
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SESSION_NAME: ${{ secrets.SESSION_NAME }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
