# .github/workflows/main.yml

name: Run HR Vision Agent

on:
  # Запуск по расписанию, каждые 20 минут
  schedule:
    - cron: '*/20 * * * *'
  
  # Позволяет запускать этот воркфлоу вручную со страницы Actions
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
    - name: 1. Checkout repository
      # Скачиваем код из репозитория
      uses: actions/checkout@v4

    - name: 2. Set up Python
      # Устанавливаем нужную версию Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Можете указать вашу версию

    - name: 3. Install dependencies
      # Устанавливаем библиотеки из requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 4. Run Python script
      # Запускаем главный скрипт
      run: python main.py
      env:
        # Передаем секреты в окружение скрипта
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SESSION_NAME: ${{ secrets.SESSION_NAME }}