# .github/workflows/main.yml

name: Run HR Vision Agent

on:
  schedule:
    - cron: '*/20 * * * *'
  
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 👇👇👇 ДОБАВЛЕННЫЙ ШАГ ДЛЯ ОТЛАДКИ 👇👇👇
    - name: 3. Debug secrets
      run: |
        echo "GEMINI_API_KEY is set: ${{ env.GEMINI_API_KEY != '' }}"
        echo "CLOUDFLARE_WORKER_URL is set: ${{ env.CLOUDFLARE_WORKER_URL != '' }}"
        echo "SUPABASE_URL is set: ${{ env.SUPABASE_URL != '' }}"
        echo "TELEGRAM_API_ID is set: ${{ env.TELEGRAM_API_ID != '' }}"
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
    # 👆👆👆 КОНЕЦ ОТЛАДОЧНОГО ШАГА 👆👆👆

    - name: 4. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 5. Run Python script
      run: python main.py
      env:
        # Убедитесь, что имена здесь ТОЧНО совпадают с именами в настройках репозитория
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SESSION_NAME: ${{ secrets.SESSION_NAME }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}